package com.restaurant.model.Enum;

public enum UpdateType {
    BONUS_AND_COMMISSIONS,
    DAYTIME_OVERTIME_HOURS,
    NIGHTTIME_OVERTIME_HOURS,
    SUNDAY_OVERTIME_HOURS,
    DEDUCTION,
    LEAVE_WITHOUT_PAY,
    VACATION_PAY,
    DISABILITY,
    TRANSPORTATION_ALLOWANCE

}
