package com.restaurant.model.Enum;

public enum UpdateType {
    BONOS_Y_COMISIONES,
    HORAS_EXTRAS_DIURNAS,
    HORAS_EXTRAS_NOCTURNAS,
    HORAS_EXTRAS_DOMINICALES,
    HORAS_EXTRASNOCTURNAS_DOMINICALES,
    DEDUCCIONES,
    DIA_SIN_REMUNERACION,
    VACACIONES,
    INCAPACIDAD,
    AUXILIO_DE_TRANSPORTE,
    PRIMA,
    CESANTIAS,
    ARL,
    EPS,
    PENSION,
    CCF
}
