# spring.application.nameSupplier=restaurant
# spring.data.mongodb.uri=mongodb+srv://carlos:BEuWvDfNd9HwfwLn@cluster0.5expw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# spring.data.mongodb.database=elalero
spring:
  application:
    name: restaurant
  data:
    mongodb:
      uri:mongodb+srv://Jahn:jahn.elalero@cluster0.5expw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    Database: elalero