# spring.application.name=restaurant
spring:
  application:
    name: restaurant

Spring:
  data:
    mongodb:
      uri:mongodb+srv://jahn:jahn.elalero@cluster0.5expw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
