spring:
  config:
    import: configuration.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${data.email}
    password: ${data.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  application:
    name: restaurant
  data:
    mongodb:
      uri: ${data.url}
      database: ${data.database}
