my:
  test:
    imageOne:
      route: src/test/java/com/restaurant/images/images.webp
  userOne:

data:
  email: equiporoblox520@gmail.com
  password: vzjq tyle doef ihzv
  url: mongodb+srv://carlos:BEuWvDfNd9HwfwLn@cluster0.5expw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  database: elalero
  host: smtp.gmail.com
  port: 587
  name: restaurant
